"""
Reads video IDs from a jsonl file and fetches only auto-generated transcripts
using youtube_transcript_api. Outputs a JSON file: {video_id: transcript_text}.
"""
import json
import os
import time

import pandas as pd
from dotenv import load_dotenv
from tqdm import tqdm

if os.path.isdir("../data/"):
    os.chdir("../")

load_dotenv()

from src.transcripts_collection import fetch_auto_transcript

ERROR_MESSAGES = {
    "[video_not_available]", "[video_private]", "[video_age_restricted]", "[live_video]",
    "[copyright_grounds]", "[copyright_claims]", "[video_removed]", "[suicide_self_harm_topics]",
    "[video_graphic_or_violent]", "[transcripts_disabled]", "[no_autogenerated_transcript]",
}


def merge_transcripts_into_videos(results: dict, video_filename: str) -> None:
    """Merge fetched transcripts into the video jsonl, tagging new rows'
    'generated_by' as 'youtube_transcript_api' (error messages go to
    'error_transcript' instead, matching the notebook 01 behavior)."""
    if not results:
        return

    video_path = f"data/youtube/videos/{video_filename}.jsonl"
    videos_df = pd.read_json(video_path, lines=True)

    for col in ("transcript", "error_transcript", "generated_by"):
        if col not in videos_df.columns:
            videos_df[col] = pd.NA

    for video_id, text in results.items():
        mask = videos_df["videoId"] == video_id
        if not mask.any():
            continue
        if text in ERROR_MESSAGES:
            videos_df.loc[mask, "error_transcript"] = text
            videos_df.loc[mask, "transcript"] = ""
        else:
            videos_df.loc[mask, "transcript"] = text
            videos_df.loc[mask, "generated_by"] = "youtube_transcript_api"

    videos_df.to_json(video_path, lines=True, orient="records", force_ascii=False)
    print(f"Merged {len(results)} transcripts into {video_path}")


def main():
    video_filename = "pp_videos_2024"
    json_output = "pp_transcripts_2024"

    results = {}

    # load JSON
    if os.path.exists(f"data/youtube/transcripts/{json_output}.json"):
        with open(f"data/youtube/transcripts/{json_output}.json") as f:
            results = json.load(f)

    video_df = pd.read_json(f"data/youtube/videos/{video_filename}.jsonl", lines=True)
    video_ids = list(set(video_df["videoId"]) - set(results.keys()))

    print(f"{len(video_ids)}/{len(video_df)} video IDs. Fetching transcripts...\n")

    for i, vid in enumerate((pbar := tqdm(video_ids, desc="Fetching transcripts"))):
        pbar.set_postfix(video=vid)
        try:
            text = fetch_auto_transcript(vid)
            if text is not None:
                results[vid] = text
                # Save JSON
                with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
                    json.dump(results, f, ensure_ascii=False, indent=2)
        except KeyboardInterrupt as e:
            with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
                time.sleep(5)
            merge_transcripts_into_videos(results, video_filename)
            raise e

    # Save JSON
    with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"\nDone. {len(results)}/{len(video_ids)} transcripts saved to '{json_output}.json'")

    merge_transcripts_into_videos(results, video_filename)


if __name__ == "__main__":
    main()