"""
Reads video IDs from data/youtube/videos/{channel_type}_videos_{year}.jsonl and
fetches only auto-generated transcripts using youtube_transcript_api. Saves them
to data/youtube/transcripts/{channel_type}_transcripts_{year}.json
({video_id: transcript_text}) and merges them into the video file.
"""
import argparse
import json
import os
import time

import pandas as pd
from dotenv import load_dotenv
from tqdm import tqdm

if os.path.isdir("../data/"):
    os.chdir("../")

load_dotenv()

from src.transcripts_collection import fetch_auto_transcript
from scripts.project_config import CHANNEL_TYPES, YEARS

ERROR_MESSAGES = {
    "[video_not_available]", "[video_private]", "[video_age_restricted]", "[live_video]",
    "[copyright_grounds]", "[copyright_claims]", "[video_removed]", "[suicide_self_harm_topics]",
    "[video_graphic_or_violent]", "[transcripts_disabled]", "[no_autogenerated_transcript]",
    "[fetch_failed]",
}


def merge_transcripts_into_videos(results: dict, video_filename: str) -> None:
    """Merge fetched transcripts into the video jsonl, tagging new rows'
    'generated_by' as 'youtube_transcript_api' (error messages go to
    'error_transcript' instead, matching the notebook 01 behavior)."""
    if not results:
        return

    video_path = f"data/youtube/videos/{video_filename}.jsonl"
    videos_df = pd.read_json(video_path, lines=True)

    for col in ("transcript", "error_transcript", "generated_by"):
        if col not in videos_df.columns:
            videos_df[col] = pd.NA

    for video_id, text in results.items():
        mask = videos_df["videoId"] == video_id
        if not mask.any():
            continue
        if text in ERROR_MESSAGES:
            videos_df.loc[mask, "error_transcript"] = text
            videos_df.loc[mask, "transcript"] = ""
        else:
            videos_df.loc[mask, "transcript"] = text
            videos_df.loc[mask, "generated_by"] = "youtube_transcript_api"

    videos_df.to_json(video_path, lines=True, orient="records", force_ascii=False)
    print(f"Merged {len(results)} transcripts into {video_path}")


def collect_transcripts(channel_type: str, year: str) -> None:
    video_filename = f"{channel_type}_videos_{year}"
    json_output = f"{channel_type}_transcripts_{year}"

    results = {}

    # load JSON
    if os.path.exists(f"data/youtube/transcripts/{json_output}.json"):
        with open(f"data/youtube/transcripts/{json_output}.json") as f:
            results = json.load(f)

    video_df = pd.read_json(f"data/youtube/videos/{video_filename}.jsonl", lines=True)
    video_ids = list(set(video_df["videoId"]) - set(results.keys()))

    print(f"{len(video_ids)}/{len(video_df)} video IDs. Fetching transcripts...\n")

    for i, vid in enumerate((pbar := tqdm(video_ids, desc="Fetching transcripts"))):
        pbar.set_postfix(video=vid)
        try:
            text = fetch_auto_transcript(vid)
            if text is not None:
                results[vid] = text
                # Save JSON
                with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
                    json.dump(results, f, ensure_ascii=False, indent=2)
        except KeyboardInterrupt as e:
            with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
                time.sleep(5)
            merge_transcripts_into_videos(results, video_filename)
            raise e

    # Save JSON
    with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"\nDone. {len(results)}/{len(video_ids)} transcripts saved to '{json_output}.json'")

    merge_transcripts_into_videos(results, video_filename)


def main():
    parser = argparse.ArgumentParser(description="Fetch YouTube auto-generated transcripts.")
    parser.add_argument("--year", choices=YEARS, default=None, help="restrict to one year (default: all)")
    parser.add_argument("--channel_type", choices=CHANNEL_TYPES, default=None,
                        help="restrict to one channel type (default: all)")
    args = parser.parse_args()

    os.makedirs("data/youtube/transcripts", exist_ok=True)
    for year in [args.year] if args.year else YEARS:
        for channel_type in [args.channel_type] if args.channel_type else CHANNEL_TYPES:
            collect_transcripts(channel_type, year)


if __name__ == "__main__":
    main()