"""
YouTube Transcript Fetcher
--------------------------
Fetches only auto-generated transcripts for a YouTube video ID using
youtube_transcript_api, through a proxy.
"""
import os
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from youtube_transcript_api.proxies import GenericProxyConfig


def transcript_to_text(transcript) -> str:
    """Join transcript segments into a single clean string (no timestamps)."""
    return " ".join([entry.text.strip() for entry in transcript])


def fetch_auto_transcript(video_id: str) -> str | None:
    """
    Fetch the auto-generated transcript for a video.
    Returns the transcript text, or None if unavailable.
    Only considers transcripts where is_generated=True.
    """
    proxy_config = GenericProxyConfig(
        http_url=os.environ["PROXY_HTTP_URL"],
        https_url=os.environ["PROXY_HTTPS_URL"],
    )

    ytt_api = YouTubeTranscriptApi(proxy_config=proxy_config)
    try:
        transcript_list = ytt_api.list(video_id)
    except TranscriptsDisabled:
        print(f"  [SKIP] {video_id} — transcripts disabled")
        return "[transcripts_disabled]"
    except Exception as e:
        print(f"  [ERROR] {video_id} — {e}")
        print(f"verify video at https://www.youtube.com/watch?v={video_id}")
        if "The video is no longer available" in str(e):
            return f"[video_not_available]"
        if "This video is private" in str(e):
            return f"[video_private]"
        if "This video is age-restricted" in str(e):
            return f"[video_age_restricted]"
        if "This live event will begin in a few moments." in str(e):
            return f"[live_video]"
        if "copyright grounds" in str(e):
            return f"[copyright_grounds]"
        if "copyright claim" in str(e):
            return f"[copyright_claims]"
        if "This video has been removed by the uploader" in str(e):
            return f"[video_removed]"
        if "contain suicide or self-harm topics" in str(e):
            return f"[suicide_self_harm_topics]"
        if "The uploader has not made this video available" in str(e):
            return f"[video_not_available]"
        if "The following content may contain graphic or violent imagery" in str(e):
            return f"[video_graphic_or_violent]"
        return None

    # Try to find an auto-generated transcript in any language
    for transcript in transcript_list:
        if transcript.is_generated:
            try:
                data = transcript.fetch()
                return transcript_to_text(data)
            except Exception as e:
                print(f"  [ERROR] {video_id} — could not fetch auto transcript: {e}")
                print(f"verify video at https://www.youtube.com/watch?v={video_id}")
                return None

    print(f"  [SKIP] {video_id} — no auto-generated transcript found")
    return "[no_autogenerated_transcript]"
