"""
YouTube Transcript Fetcher
--------------------------
Reads video IDs from a CSV file and fetches only auto-generated transcripts
using youtube_transcript_api. Outputs a JSON file: {video_id: transcript_text}.

CSV format expected:
  - column named 'videoId'
"""
import json
import os
import sys
import pandas as pd
import argparse
import time
from youtube_transcript_api import YouTubeTranscriptApi, NoTranscriptFound, TranscriptsDisabled
from youtube_transcript_api.proxies import GenericProxyConfig, WebshareProxyConfig
from tqdm import tqdm
if os.path.isdir("../data/"):
    os.chdir("../")


def transcript_to_text(transcript) -> str:
    """Join transcript segments into a single clean string (no timestamps)."""
    return " ".join([entry.text.strip() for entry in transcript])


def fetch_auto_transcript(video_id: str) -> str | None:
    """
    Fetch the auto-generated transcript for a video.
    Returns the transcript text, or None if unavailable.
    Only considers transcripts where is_generated=True.
    """
    proxy_config = GenericProxyConfig(
        http_url="http://***REMOVED***@pr.oxylabs.io:7777",
        https_url="https://***REMOVED***@pr.oxylabs.io:7777",
    )

    proxy_config = GenericProxyConfig(
        http_url= "http://***REMOVED***@rp.evomi.com:1000",
        https_url= "http://***REMOVED***@rp.evomi.com:1000"
    )

    proxy_config = GenericProxyConfig(
        http_url="http://***REMOVED***@gw.dataimpulse.com:823",
        https_url="http://***REMOVED***@gw.dataimpulse.com:823"
    )

    proxy_config = GenericProxyConfig(
        http_url="http://***REMOVED***@proxy.smartproxy.net:3120",
        https_url="http://***REMOVED***@proxy.smartproxy.net:3120"
    )

    ytt_api = YouTubeTranscriptApi(proxy_config=proxy_config)
    #ytt_api = YouTubeTranscriptApi()
    try:
        transcript_list = ytt_api.list(video_id)
    except TranscriptsDisabled:
        print(f"  [SKIP] {video_id} — transcripts disabled")
        return "[transcripts_disabled]"
    except Exception as e:
        print(f"  [ERROR] {video_id} — {e}")
        print(f"verify video at https://www.youtube.com/watch?v={video_id}")
        if "The video is no longer available" in str(e):
            return f"[video_not_available]"
        if "This video is private" in str(e):
            return f"[video_private]"
        if "This video is age-restricted" in str(e):
            return f"[video_age_restricted]"
        if "This live event will begin in a few moments." in str(e):
            return f"[live_video]"
        if "copyright grounds" in str(e):
            return f"[copyright_grounds]"
        if "copyright claim" in str(e):
            return f"[copyright_claims]"
        if "This video has been removed by the uploader" in str(e):
            return f"[video_removed]"
        if "contain suicide or self-harm topics" in str(e):
            return f"[suicide_self_harm_topics]"
        if "The uploader has not made this video available" in str(e):
            return f"[video_not_available]"
        if "The following content may contain graphic or violent imagery" in str(e):
            return f"[video_graphic_or_violent]"
        return None

    # Try to find an auto-generated transcript in any language
    for transcript in transcript_list:
        if transcript.is_generated:
            try:
                data = transcript.fetch()
                return transcript_to_text(data)
            except Exception as e:
                print(f"  [ERROR] {video_id} — could not fetch auto transcript: {e}")
                print(f"verify video at https://www.youtube.com/watch?v={video_id}")
                return None

    print(f"  [SKIP] {video_id} — no auto-generated transcript found")
    return "[no_autogenerated_transcript]"


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    video_filename = "pp_videos_2024"
    json_output = "pp_transcripts_2024"

    results = {}

    # load JSON
    if os.path.exists(f"data/youtube/transcripts/{json_output}.json"):
        with open(f"data/youtube/transcripts/{json_output}.json") as f:
            results = json.load(f)

    video_df = pd.read_csv(f"data/youtube/videos/{video_filename}.csv")
    video_ids = list(set(video_df["videoId"]) - set(results.keys()))

    print(f"{len(video_ids)}/{len(video_df)} video IDs. Fetching transcripts...\n")

    for i, vid in enumerate((pbar := tqdm(video_ids, desc="Fetching transcripts"))):
        pbar.set_postfix(video=vid)
        try:
            text = fetch_auto_transcript(vid)
            if text is not None:
                results[vid] = text
                # Save JSON
                with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
                    json.dump(results, f, ensure_ascii=False, indent=2)
        except KeyboardInterrupt as e:
            with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
                time.sleep(5)
            raise e


    # Save JSON
    with open(f"data/youtube/transcripts/{json_output}.json", "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"\nDone. {len(results)}/{len(video_ids)} transcripts saved to '{json_output}.json'")

if __name__ == "__main__":
    main()
